services:
  fastapi:
    image: fastapi-docker:develop
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    tty: true
    stdin_open: true
    command: /bin/bash